//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace procluentdbfirstuygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakanlık
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bakanlık()
        {
            this.Vergiler = new HashSet<Vergiler>();
        }
    
        public int bakanlikID { get; set; }
        public string bakanlikAdi { get; set; }
        public string daireBaskanligi { get; set; }
        public Nullable<int> ciro { get; set; }
        public string merkez { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vergiler> Vergiler { get; set; }
    }
}
